const queries = {
    createItemsTable:`
        CREATE TABLE items (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR(100) NOT NULL,
            thumbnail TEXT,
            ducat_price VARCHAR(100) NOT NULL,
            credit_price VARCHAR(100) NOT NULL,
            last_date DATE
        );
    `,
    createInventoryTable:`
        CREATE TABLE inventory (
            name VARCHAR(100) NOT NULL PRIMARY KEY
        );
    `,
    dropItemsTable:`
        DROP TABLE IF EXISTS items;
    `,
    dropInventoryTable:`
        DROP TABLE IF EXISTS inventory;
    `,
    insertItem:`
        INSERT INTO items (
            name,
            thumbnail,
            ducat_price,
            credit_price,
            last_date)
        VALUES ($1, $2, $3, $4, $5);
    `,
    insertInventory:`
        INSERT INTO inventory (
            name)
        VALUES ($1);
    `,
    findItem:`
        SELECT * FROM items
        WHERE name = $1;
    `,
    getItems:`
        SELECT * FROM items;
    `,
    getInventory:`
        SELECT * FROM inventory;
    `,
    getNewItem:`
        SELECT * FROM items
        ORDER BY id DESC
        LIMIT 1;
    `
}

export default queries;